spring:
  datasource:
    url: jdbc:mysql://192.168.131.186:3306/learn_self?useSSL=false&characterEncoding=utf8
    username: root
    password: lpycHuEcU3<8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:org/self/learn/dao/mapper/*.xml
